from datetime import time, timedelta

FORM_DATE_FORMAT: str = "%Y-%m"
FORM_COMPLETE_DATE_FORMAT: str = "%Y-%m-%d"
SCHEDULE_RECORDS_DATE_FORMAT: str = "%m-%Y"
SCHEDULE_RECORDS_TIME_FORMAT: str = "%H:%M:%S"

MONTH_CUT: int = 26

STANDARD_CHECK_IN_TUESDAY_TO_FRIDAY = time(9, 0, 0)
STANDARD_CHECK_IN_MONDAY_AND_SATURDAY = time(10, 0, 0)
STANDARD_CHECK_OUT_WEEKDAY = time(18, 30, 0)
STANDARD_CHECK_OUT_SATURDAY = time(14, 0, 0)
STANDARD_LUNCH_BREAK_START = time(14, 0, 0)
STANDARD_LUNCH_BREAK_DURATION = timedelta(minutes=45)
STANDARD_TOTAL_HOURS_WORKED_MONDAY = timedelta(hours=7, minutes=45)
STANDARD_TOTAL_HOURS_WORKED_TUESDAY_TO_FRIDAY = timedelta(hours=8, minutes=45)
STANDARD_TOTAL_HOURS_WORKED_SATURDAY = timedelta(hours=1, minutes=15)