CERTAINTY: float = .5
CONFIDENCE_LEVEL: float = .7
DAYS_OF_ANTICIPATION: int = 20
DAYS_TO_LAST: int = 30
DOWN_COLOR: str = 'red'
UP_COLOR: str = 'green'
DECAY = 0.92
FEW_DATA_POINTS_PONDERATOR_LINEAR_COEFFICIENTS: tuple[float] = (.15, -.6)